import './globals.css'
import type { Metadata } from 'next'

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import WalletContextProvider from '@/components/WalletContextProvider';
// import { ContextProvider } from '@/components/ContextProvider';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <Header></Header>
          <WalletContextProvider>
            {children}
          </WalletContextProvider>
          <Footer></Footer>
      </body>
    </html>
  )
}
